/**
 * Apendice A da especificacao — Slack ID -> nome completo.
 *
 * Fonte unica da lista de pessoas. `U09F9LWM6MC` (Suzana Martins Tavares) e a
 * administradora; todos os demais entram como `requester`.
 *
 * Para adicionar alguem: acrescente a linha aqui e rode `npm run seed` de novo
 * (e idempotente, nao duplica ninguem).
 */
export interface SeedUser {
  slackId: string;
  name: string;
}

export const USERS: SeedUser[] = [
  { slackId: 'U07KP9J5BLP', name: 'Rafaela Alves Mendes' },
  { slackId: 'U07KPE840MD', name: 'Erick Café Santos Júnior' },
  { slackId: 'U07KX76F7D4', name: 'Leidiane Souza' },
  { slackId: 'U07KXEJU338', name: 'Alberto Luiz Marinho Batista' },
  { slackId: 'U07L4D3EWJW', name: 'Jonathan Henrique da Conceição Silva' },
  { slackId: 'U07L6EAUS75', name: 'Maria Taciane Pereira Barbosa' },
  { slackId: 'U07LGG4RPK3', name: 'José Fernando dos Santos Santana Ramos' },
  { slackId: 'U07LP4JSN9K', name: 'João Antonio Tavares Santos' },
  { slackId: 'U07LSKN7SNL', name: 'Rômulo Jose Santos Lisboa' },
  { slackId: 'U07Q8NT7J1Y', name: 'Ravy Thiago Vieira da Silva' },
  { slackId: 'U07Q9HE3KGA', name: 'Amanda Santos Costa' },
  { slackId: 'U081ZP68CA1', name: 'Tomás Azevedo Santos' },
  { slackId: 'U082F9GGMSM', name: 'Maria Nobre Farias de França' },
  { slackId: 'U0875QNU02K', name: 'Kauanne Iwashita da Silva' },
  { slackId: 'U08762E1PMM', name: 'João Victor Santos da Silva' },
  { slackId: 'U087E6YNPRD', name: 'Ana Paula Amaral Santos Ismerim' },
  { slackId: 'U087HDEARA9', name: 'Kemilly Rafaelly Souza Silva' },
  { slackId: 'U087HG1B4DB', name: 'Maria Tatiane Oliveira Santos' },
  { slackId: 'U087M32A18B', name: 'Luan Santos de Oliveira' },
  { slackId: 'U087M7GCNMC', name: 'Valesca Meirelle Bezerra Vitória' },
  { slackId: 'U087P8JF97F', name: 'Eliene da Silva Santos' },
  { slackId: 'U088986S1L0', name: 'Jordelle Meygre Costa de Oliveira' },
  { slackId: 'U088B372R40', name: 'Mariane Santos Sousa' },
  { slackId: 'U088MU33XRC', name: 'Bruna Cândido de Lima' },
  { slackId: 'U0895CZ8HU7', name: 'Carlos Eduardo Silva de Oliveira' },
  { slackId: 'U089NSW1BDG', name: 'Caique dos Santos da Silva' },
  { slackId: 'U08B1MQJL3C', name: 'Robéria Gilo da Silva' },
  { slackId: 'U08B2NHAH8C', name: 'Thayane Mayara dos Santos' },
  { slackId: 'U08E4LNLG06', name: 'Luiz Fellipe Guedes Santos Silva' },
  { slackId: 'U08E8GH19TP', name: 'Thalys Gomes dos Santos' },
  { slackId: 'U08EB943ZCJ', name: 'Paulo Cesar da Silva Santos Junior' },
  { slackId: 'U08EHG788DV', name: 'Claudio Bispo dos Santos' },
  { slackId: 'U08ERHMN6F9', name: 'Ana Luiza dos Santos' },
  { slackId: 'U08EYMYMXNW', name: 'Danrley Firmino dos Santos' },
  { slackId: 'U08F7PSCPK6', name: 'Sabrina Domingos Santos' },
  { slackId: 'U08F8T8SMNE', name: 'Yasmim da Rocha Bezerra Barbosa' },
  { slackId: 'U08F9KK0AAG', name: 'Ana Clara de Matos Chagas' },
  { slackId: 'U08H0PHPAMC', name: 'Ludmylla Wolpert Melo' },
  { slackId: 'U08JFCGBFSA', name: 'Anny Karoline Andrade Santos' },
  { slackId: 'U08JJ6JMH50', name: 'Leticia Seixas Santos' },
  { slackId: 'U08JJ7VF0N6', name: 'Nathália Vieira Lima' },
  { slackId: 'U08JJH9BWP5', name: 'Gessyca Nayara Rocha Santos' },
  { slackId: 'U08K69RC01H', name: 'Letícia Soares Belo' },
  { slackId: 'U08M7D0EVR9', name: 'Natali de Souza Gonzaga' },
  { slackId: 'U08NLNHF29G', name: 'Bruna Rayane Oliveira dos Santos' },
  { slackId: 'U08NLQK5PEJ', name: 'Millena Sthefany dos Santos Cruz' },
  { slackId: 'U08NTGXEK26', name: 'Emanoelle Feitosa Vieira Santos' },
  { slackId: 'U08P5GH6C3Z', name: 'Giselle dos Santos Roberto' },
  { slackId: 'U08PER1QM2N', name: 'Juliene Bezerra' },
  { slackId: 'U08PPAAH5PT', name: 'Luciano Torres' },
  { slackId: 'U08PZTY2G0Y', name: 'Josimara Ferreira Monteiro' },
  { slackId: 'U08QP0KFL15', name: 'Márcio Alif Santos Silva' },
  { slackId: 'U08UMBX0CP4', name: 'Laís Manuelle Santos Pereira' },
  { slackId: 'U0922F5KB7U', name: 'Rodrigo Augusto Teixeira Dos Santos' },
  { slackId: 'U0929MZMW5C', name: 'Danielle dos Santos Silva' },
  { slackId: 'U092FQKNFPB', name: 'Deise Gislaine Silva Vitor' },
  { slackId: 'U0939HA46LW', name: 'Camilla Emanuelle Lopes De Almeida' },
  { slackId: 'U094A8J5R2L', name: 'Yuri Castro Gomes' },
  { slackId: 'U097B39GTMG', name: 'Luís Henrique Batista dos Santos' },
  { slackId: 'U09AYV61119', name: 'Lianda Melinda Santos Calixto' },
  { slackId: 'U09B6LQ3FFY', name: 'Karine Celestino Evangelista dos Santos' },
  { slackId: 'U09BMRBFRM0', name: 'Pedro Lucas Rocha da Fonseca' },
  { slackId: 'U09DHA4MV52', name: 'João Ricardo Dantas Albuquerque' },
  { slackId: 'U09ED214T6W', name: 'Maryanna Francielly Trajano da Silva' },
  { slackId: 'U09F9LWM6MC', name: 'Suzana Martins Tavares' },
  { slackId: 'U09G04R3CNP', name: 'Gessica Queiroz' },
  { slackId: 'U09JGAFFZB6', name: 'Camille Kauane da Silva Nunes' },
  { slackId: 'U09QM89NV5W', name: 'Alcina' },
  { slackId: 'U0A0D0J2E31', name: 'Raquele Fragoso da Silva' },
  { slackId: 'U0A1P79UK0T', name: 'Sandra da Conceição Freitas' },
  { slackId: 'U0A1VJ2Q4R0', name: 'Rosilene Martins da Silva' },
  { slackId: 'U0A2PUWCUKS', name: 'Ane Caroline Pereira Martér' },
  { slackId: 'U0A3P2QB5P0', name: 'Hugo Castro Lopes' },
  { slackId: 'U0A5YLESW1E', name: 'Yasmin Abilia Ferro Da Silva' },
  { slackId: 'U0A6WDA1LSF', name: 'Edna Lopes da Silva' },
  { slackId: 'U0AA4R2LSUS', name: 'Luciene da Silva Nascimento' },
  { slackId: 'U0AHTBS64KH', name: 'Jaíne Mariana Rodrigues Mendonça' },
  { slackId: 'U0AKHDX4G83', name: 'Lays da Silva Vieira' },
  { slackId: 'U0AKMRS669L', name: 'Marília Alice dos Santos Silva' },
  { slackId: 'U0AKMS2LNEA', name: 'Eduarda Pereira Costa Silva' },
  { slackId: 'U0AL2NDNH09', name: 'Maria Cicília Brito Veiga' },
  { slackId: 'U0AMN750JT0', name: 'Fabia Batista da Silva' },
  { slackId: 'U0AMSCAC1HR', name: 'Thamires Emanuelle da Silva' },
  { slackId: 'U0AP3LJ355L', name: 'Maria Jeane Da Silva Santos' },
  { slackId: 'U0ARN2C0YLT', name: 'Joanna Roberta de Queiroz Viana' },
  { slackId: 'U0ASUE1GNUA', name: 'Maria Fernanda Gomes Vieira' },
  { slackId: 'U0ASY08QHTN', name: 'Josenildo Alves da Silva Júnior' },
  { slackId: 'U0AT1KKLWNS', name: 'Shayane Oliveira Ferreira' },
  { slackId: 'U0ATLF85Z9U', name: 'Brunna Isabelly Silva Lima' },
  { slackId: 'U0B1D2NM47M', name: 'Nayara Soares Kimura' },
  { slackId: 'U0B8A9PLC6B', name: 'Sione Barbosa da Silva' },
  { slackId: 'U0B8TL364P3', name: 'Samuel Monteiro da Silva' },
  { slackId: 'U0BA9MCGX6K', name: 'Luciene Tayná Félix da Silva' },
  { slackId: 'U0BAT0U8DS5', name: 'Juliana Francine Marques da Silva' },
  { slackId: 'U0BQ87WPVQE', name: 'Alekson Fernandes Moura' },
  { slackId: 'U0BGA5QHHLJ', name: 'Amanda de Araújo Santos' },
  { slackId: 'U0BG84A7VF0', name: 'Auda da Conceição Santos' },
  { slackId: 'U0BD3P15E2J', name: 'Bruna Soares Siqueira' },
  { slackId: 'U0BBSVDGNP5', name: 'Caroline Leite dos Santos' },
  { slackId: 'U0BFUPEQ6B1', name: 'Crislaine Freire dos Santos' },
  { slackId: 'U0BDA1F9PLL', name: 'Edlane Silva de Lima' },
  { slackId: 'U0BBWRCFVM0', name: 'Evellyn Vitória Nunes Santos' },
  { slackId: 'U0BLWU0UG9E', name: 'Jayane da Silva Dias' },
  { slackId: 'U0BGDSAR0VA', name: 'Juliene Reis Ferreira' },
  { slackId: 'U0BFUP1HDB9', name: 'Kledja Nunes da Silva' },
  { slackId: 'U07K7G5N0DB', name: 'Luiz Henrique Martins Tavares' },
  { slackId: 'U0BGA5FEA10', name: 'Rayanne Maria dos Santos Moca' },
  { slackId: 'U0BGKC2GLMV', name: 'Sabrina Barbosa Machado Mariano' },
  { slackId: 'U0BG84EDWVC', name: 'Tayna Monaisa Vasconcelos Santos' },
];
